---
deployment:
  tasks:


    - export DEPLOYPATH=/home/ecobricks/public_html/


    - /bin/cp -R icons $DEPLOYPATH
    - /bin/cp -R svgs $DEPLOYPATH
    - /bin/cp -R webp $DEPLOYPATH
    - /bin/cp -R images $DEPLOYPATH
    - /bin/cp -R dials $DEPLOYPATH

    - /bin/cp .htaccess $DEPLOYPATH
    - /bin/cp .cpanel.yml $DEPLOYPATH
    - /bin/cp sitemap.xml $DEPLOYPATH

    - /bin/cp index.php $DEPLOYPATH
    - /bin/cp market.php $DEPLOYPATH