---
deployment:
  tasks:
    - export DEPLOYPATH=/home/ecobricks/gobrik/

    - /bin/cp -R dials $DEPLOYPATH
    - /bin/cp -R icons $DEPLOYPATH
    - /bin/cp -R images $DEPLOYPATH
    - /bin/cp -R svgs $DEPLOYPATH
    - /bin/cp -R webp $DEPLOYPATH
    - /bin/cp -R meta $DEPLOYPATH
    - /bin/cp index.php $DEPLOYPATH
    - /bin/cp market.php $DEPLOYPATH