---
deployment:
  tasks:

    - export DEPLOYPATH=/home/ecobricks/repositories/gobrik-live/

    - /bin/cp -R dials $DEPLOYPATH
    - /bin/cp -R icons $DEPLOYPATH
    - /bin/cp -R images $DEPLOYPATH
    - /bin/cp -R svgs $DEPLOYPATH
    - /bin/cp -R webp $DEPLOYPATH
    - /bin/cp -R meta $DEPLOYPATH

    - /bin/cp .cpanel.yml $DEPLOYPATH
    - /bin/cp sitemap.xml $DEPLOYPATH
    - /bin/cp arc-sw.js $DEPLOYPATH
    - /bin/cp spring-javascripts.js $DEPLOYPATH
    - /bin/cp spring-footer-stylesheet.css $DEPLOYPATH
    - /bin/cp spring-knack-stylesheet.css $DEPLOYPATH
    - /bin/cp spring-main-stylesheet.css $DEPLOYPATH
    - /bin/cp stylesheet-landing.css $DEPLOYPATH

    - /bin/cp header.php $DEPLOYPATH
    - /bin/cp core.php $DEPLOYPATH
    - /bin/cp footer.php $DEPLOYPATH
  
    - /bin/cp index.php $DEPLOYPATH
